"""アプリ全体で使用する定数."""

# ロール: 1スタッフ = 1ロール（MVP1）
ROLE_LEADER = "LEADER"
ROLE_CHECKER = "CHECKER"
ROLE_CLEANER = "CLEANER"
ROLE_CODES = (ROLE_LEADER, ROLE_CHECKER, ROLE_CLEANER)

# スキルレベル: 清掃業務全般の総合スキルを1〜5の整数で保持する
SKILL_LEVEL_MIN = 1
SKILL_LEVEL_MAX = 5
SKILL_LEVEL_DEFAULT = 3
SKILL_LEVELS = {1: "初心者", 2: "初級", 3: "標準", 4: "上級", 5: "熟練"}

# 勤怠CSVの勤務セル区分
# BLANK は「空欄」であり「休日」とは断定しない（元CSVの意味が変わっても対応できるように）
SHIFT_TYPE_TIME_RANGE = "TIME_RANGE"
SHIFT_TYPE_OTHER_DUTY = "OTHER_DUTY"
SHIFT_TYPE_BLANK = "BLANK"
SHIFT_TYPE_UNKNOWN = "UNKNOWN"
SHIFT_TYPES = (
    SHIFT_TYPE_TIME_RANGE,
    SHIFT_TYPE_OTHER_DUTY,
    SHIFT_TYPE_BLANK,
    SHIFT_TYPE_UNKNOWN,
)

# 勤怠インポートの状態: 各月ACTIVEは最大1件。再取込時は旧ACTIVEをSUPERSEDEDにする
IMPORT_STATUS_ACTIVE = "ACTIVE"
IMPORT_STATUS_SUPERSEDED = "SUPERSEDED"
IMPORT_STATUSES = (IMPORT_STATUS_ACTIVE, IMPORT_STATUS_SUPERSEDED)
